<script type="text/javascript">// <![CDATA[
require([
        'jquery',
        'Magento_Ui/js/modal/confirm'
    ],
    function($, confirmation) {
        $('.omise-cc-delete').on('click', function(event){
            event.preventDefault();
            confirmation({
                content: $.mage.__('Are you sure you want to delete this card?'),
                actions: {
                    confirm: function() {
                        $.post(event.currentTarget.attributes.getNamedItem('data-link').value, function() {
                            location.reload();
                        });
                    },
                    cancel: function(){
                        return false;
                    },
                }
            });
        });
    }
);
// ]]></script>

<?php
$cards = $block->getCards();
?>

<?php if (!empty($cards['data'])): ?>
    <div class="table-wrapper my-credit-cards">
        <table class="data table table-credit-cards" id="my-orders-table">
            <caption class="table-caption"><?=/* @noEscape */__('Stored Credit/Debit Cards')?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col card-number"><?=/* @noEscape */__('Card Number')?></th>
                    <th scope="col" class="col expire"><?=/* @noEscape */__('Expiration Date')?></th>
                    <th scope="col" class="col card-type"><?=/* @noEscape */__('Type')?></th>
                    <th scope="col" class="col actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
<?php foreach ($cards['data'] as $card): ?>
                <tr>
                    <td><?php echo ' **** **** **** ' . $card['last_digits']; ?></td>
                    <td><?php echo $card['expiration_month']; ?>/<?php echo $card['expiration_year']; ?></td>
                    <td><?php echo $card['brand'] ?></td>
                    <td><a class="omise-cc-delete" href="#" data-link="<?php echo $block->getDeleteLink($card) ?>"><?=/* @noEscape */__('Delete')?></a></td>
                </tr>
<?php endforeach;?>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <div class="message info empty"><span><?=/* @noEscape */__('You have no stored cards.')?></span></div>
<?php endif?>
