<?php
$code = $this->getMethodCode();
$backends = $this->getInstalmentBackends();
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('omise/css/offsiteinternetbankingpayment.css'); ?>" />

<ul id="payment_form_<?php echo $code; ?>" class="banks-list form-list" style="display:none;">

    <?php foreach ($backends as $backend) { ?>
        
    <li class="item">
        <input id="<?=$backend->_id;?>" type="radio" name="payment[type]" value="<?=$backend->_id;?>" />
        <label for="<?=$backend->_id;?>">
            <div class="omise-logo-wrapper <?=$backend->_bankcode;?>">
                <img class="<?=$backend->_bankcode;?>" />
            </div>
            <div class="omise-banking-text-wrapper">
                <span class="title"><?=$this->__($backend->_bankname);?></span><br/>
                <select name="payment[term_<?=$backend->_id;?>]" id="payment_term_<?=$backend->_id;?>">
                    <?php foreach ($backend->allowed_installment_terms as $termMonths) { ?>
                        <option value="<?=$termMonths;?>"><?=$termMonths;?> <?=$this->__('months');?></option>
                    <?php } ?>
                </select>
            </div>
        </label>
    </li>

    <? } ?>

</ul>
