<?php
$code = $this->getMethodCode();
// These will eventually come from capabilities API
$bankCodes = ['internet_banking_scb', 'internet_banking_ktb', 'internet_banking_bay', 'internet_banking_bbl'];
?>

<ul id="payment_form_<?php echo $code; ?>" class="banks-list form-list" style="display:none;">

    <?php foreach($bankCodes as $bankCode) {  $shortCode = str_replace('internet_banking_', '', $bankCode); ?>
    <li class="item">
        <input class="validate-one-required-by-name" id="<?=$bankCode;?>" type="radio" name="payment[bank_type]" value="<?=$bankCode;?>" />
        <label for="<?=$bankCode;?>">
            <div class="omise-logo-wrapper <?=$shortCode;?>">
                <div class="logo-<?=$shortCode;?>"></div>
            </div>
            <div class="omise-banking-text-wrapper">
                <span class="title"><?=Mage::helper('omise_gateway')->internetBankingName($bankCode);?></span><br/>
            </div>
        </label>
    </li>
    <?php } ?>


    <li>
        <span class="rate secondary-text"><?=$this->__('The bank may charge a small fee for the transaction.');?></span>
    </li>
</ul>
