<?php $_code = $this->getMethodCode(); ?>

<ul id="payment_form_<?php echo $_code; ?>" class="form-list" style="display:none;">
    <li>
        <label for="<?php echo $_code; ?>_name" class="required">
            <em>*</em><?php echo $this->__('Name'); ?>
        </label>
        <div class="input-box">
            <input id="<?php echo $_code; ?>_name" type="text"
                name="payment[name]"
                title="<?php echo $this->__('Name'); ?>"
                value="<?php echo $this->escapeHtml($this->getOmiseConvenienceStoreCustomerName()); ?>"
                maxlength="10"
                class="input-text required-entry validate-length maximum-length-10" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code; ?>_phone_number" class="required">
            <em>*</em><?php echo $this->__('Phone Number'); ?>
        </label>
        <div class="input-box">
            <input id="<?php echo $_code; ?>_phone_number" type="text"
                name="payment[phone_number]"
                title="<?php echo $this->__('Phone Number'); ?>"
                value="<?php echo $this->escapeHtml($this->getOmiseConvenienceStorePhoneNumber()); ?>"
                maxlength="11"
                class="input-text required-entry validate-length maximum-length-11 minimum-length-10 validate-digits" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code; ?>_email" class="required">
            <em>*</em><?php echo $this->__('Email'); ?>
        </label>
        <div class="input-box">
            <input id="<?php echo $_code; ?>_email" type="text"
                name="payment[email]"
                title="<?php echo $this->__('Email'); ?>"
                value="<?php echo $this->escapeHtml($this->getOmiseConvenienceStoreEmail()); ?>"
                maxlength="50"
                class="input-text required-entry validate-omise-email validate-length maximum-length-50 minimum-length-6" />
        </div>
    </li>
</ul>
<script type="text/javascript">
    Validation.add('validate-omise-email', 'Please enter a valid email address.', function(v) {
        return Validation.get('IsEmpty').test(v) || /^([a-z0-9]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*@([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*\.(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]){2,})$/i.test(v)
    })
</script>