<?php $_code = $this->getMethodCode(); ?>

<ul id="payment_form_<?php echo $_code; ?>" class="form-list" style="display:none;">
    <!-- True money phone number form-->
    <li>
        <label for="<?php echo $_code; ?>_phone_number" class="required">
            <em>*</em><?php echo $this->__('Phone Number'); ?>
        </label>
        <div class="input-box">
            <input id="<?php echo $_code; ?>_phone_number" type="text"
                name="payment[phone_number]"
                title="<?php echo $this->__('Phone Number'); ?>"
                value="<?php echo $this->escapeHtml($this->getOmiseTruePhoneNumber()); ?>"
                maxlength="10"
                class="input-text required-entry validate-length maximum-length-10 minimum-length-10 validate-digits" />
        </div>
    </li>
</ul>