<div id="omise-reorder" class="page messages">
            <div role="alert" class="messages">
                <div class="message-warning warning message">
                    <span><?=__('Your payment takes more time than expected. If you cancelled your payment, you can reorder by clicking this button');?></span><button class="action secondary" ><?=__('Reorder');?></button>
                </div>
            </div>
        </div>

<div id="omise-confirm-info">
    <div id="omise-loader-box"></div><span class="omise-confirm-text" data-bind="i18n: 'Please wait, your payment is being verified'"></span>
</div>

<div id="omise-payment-confirmed" style="display: none">
    Payment successful
</div>


<script>
    var require = window.top.require;
    require(['jquery'], function ($, redirectOnSuccess) {
        'use strict';
        counter = 0;
        var confirmInterval = setInterval(function() {
            if (++counter === 5) {
                $('#omise-reorder"').show();
            }

            $.get('<?=$block->getCheckPaymentStatusUrl();?>', data => {
                if (data === true) {
                    $('#omise-payment-confirmed').show()
                    $('#omise-confirm-info').hide();
                    $('#omise-reorder"').hide();

                    clearInterval(confirmInterval);
                }
            });
        }, 1000);
    });
</script>
