<p>
    <?= $block->escapeHtml(__('Amount to pay')) ?>: 
    <strong>
        <?= $block->escapeHtml($block->getOrderAmount()) ?></b>
    </strong>
<p style="margin:.5rem 0"><?= $block->escapeHtml(__('PayNow QR Code.')); ?></p>
<div><img src="<?= $block->escapeHtml($block->getImageCode()) ?>" /></div>
<p>
    <button 
        class="action secondary" 
        onclick="window.print ? window.print() : alert('Print not available')">
        <?= $block->escapeHtml(__('Print'))?>
    </button>
</p>
<p>
    <strong>
        <i>Note:</i>
    </strong> 
    On your bank app, you will see the payee as <strong>Opn Payments SG Pte. Ltd“</strong>. 
    Opn Payments is our authorized payment processor to accept PayNow on our behalf.
</p>
<p><strong><i>Supported Banks:</i></strong></p>
<p style="max-width:420px">
    <img src="<?= $block->escapeHtml($block->getViewFileUrl('Omise_Payment::images/paynow_supportedbanks.png')); ?>" />
</p>
