<div id="qr-info">
    <p>
        <?= $block->escapeHtml(__('Amount to pay')) ?>: 
        <strong>
            <?= $block->escapeHtml($block->getOrderAmount()) ?>
            </b>
        </strong>
    <p style="margin:.5rem 0"><?= $block->escapeHtml(__('PromptPay QR Code.')); ?></p>
    <div><img id="img_payment_code" src="<?= $block->escapeHtml($block->getImageCode()) ?>" /></div>
    <p>
        Payment expires in: <span id="countdown"></span>
    </p>
    <p>
        <button class="action secondary" onclick="window.print ? window.print() : alert('Print not available')">
        <?= $block->escapeHtml(__('Print'))?></button>
    </p>

    <div style="padding: 15px; margin: 20px 0; border: 1px solid black">
        <p><strong>To make payment:</strong></p>
        <ol style="margin-bottom: 0px; padding: 0px 15px;">
            <li>Download the QR code or open your preferred bank app to scan it</li>
            <li>Check that the payment details are correct</li>
            <li>Import the QR code image into your bank app or scan the QR code with your bank app to pay</li>
            <li>Share the payment slip from your bank app to the seller</li>
        </ol>
    </div>
</div>

<script>
(function () {
    let countDownInterval;

    function calculateCountdown() {
        const currentDateTime = new Date();
        const expiresAtDateTime = new Date("<?= $block->escapeHtml($block->getChargeExpiresAt()) ?>");
        const difference = expiresAtDateTime - currentDateTime;
        const hours = Math.floor((difference % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        const minutes = Math.floor((difference % (1000 * 60 * 60)) / (1000 * 60));
        const seconds = Math.floor((difference % (1000 * 60)) / 1000);
        return { hours, minutes, seconds };
    }

    function padZero(num) {
        return num.toString().padStart(2, '0');
    }

    function hideQrInfo() {
        const element = document.getElementById('qr-info')
        element.style.display = 'none'
    }

    function updateCountdown() {
        const countdownDisplay = document.getElementById('countdown');
        if(!countdownDisplay) {
            return;
        }

        const { hours, minutes, seconds } = calculateCountdown();

        if (hours + minutes + seconds < 0) {
            if(countDownInterval) {
                clearInterval(countDownInterval)
            }
            hideQrInfo()
            return;
        }

        countdownDisplay.innerHTML = `${padZero(hours)}:${padZero(minutes)}:${padZero(seconds)}`;
        if (!countDownInterval) {
            countDownInterval = setInterval(updateCountdown, 1000);
        }
    }

    updateCountdown()
})()
</script>
