<p>
    <?= $block->escapeHtml(__('Amount to pay')) ?>: 
    <strong>
        <?= $block->escapeHtml($block->getOrderAmount()) ?>
        </b>
    </strong>
<p style="margin:.5rem 0"><?= $block->escapeHtml(__('PromptPay QR Code.')); ?></p>
<div><img id="img_payment_code" src="<?= $block->escapeHtml($block->getImageCode()) ?>" /></div>
<p>
    Payment expires at: <?= $block->escapeHtml($block->getChargeExpiresAt()); ?>
</p>
<p>
    <button class="action secondary" onclick="window.print ? window.print() : alert('Print not available')">
    <?= $block->escapeHtml(__('Print'))?></button>
</p>

<div style="padding: 15px; margin: 20px 0; border: 1px solid black">
    <p><strong>To make payment:</strong></p>
    <ul style="list-style: auto; margin-bottom: 0px; padding: 0px 15px;">
        <li>Download the QR code or open your preferred bank app to scan it</li>
        <li>Check that the payment details are correct</li>
        <li>Import the QR code image into your bank app or scan the QR code with your bank app to pay</li>
        <li>Share the payment slip from your bank app to the seller</li>
    </ul>
</div>
