<p><?=/* @noEscape */
    __('To finish payment, print the code below and bring it to make payment in any Tesco Lotus Store.
        Code is valid for the next <b>24 hours only</b>. After that time your order will be canceled.'); ?>
</p>
<p style="margin:.5rem 0">
    <?=/* @noEscape */__('Amount to pay') ?>: <strong><?= $block->escapeHtml($block->getOrderAmount()) ?></b></strong>
<div><?=/* @noEscape */ $block->getOfflineCode()  ?></div>
<p>
    <button 
        class="action secondary" 
        onclick="window.print ? window.print() : alert('Print not available')"><?=/* @noEscape */__('Print')?>
    </button>
</p>
