<?php
$code = $this->getMethodCode();
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('omise/css/offsiteinternetbankingpayment.css'); ?>" />

<ul id="payment_form_<?php echo $code; ?>" class="form-list" style="display:none;">
    <!-- SCB -->
    <li class="item">
        <input id="internet_banking_scb" type="radio" name="offsite" value="internet_banking_scb" />
        <label for="internet_banking_scb">
            <div class="omise-logo-wrapper scb">
                <img class="scb" />
            </div>
            <span>Siam Commercial Bank</span>
        </label>
    </li>

    <!-- KTB -->
    <li class="item">
        <input id="internet_banking_ktb" type="radio" name="offsite" value="internet_banking_ktb" />
        <label for="internet_banking_ktb">
            <div class="omise-logo-wrapper ktb">
                <img class="ktb" />
            </div>
            <span>Krungthai Bank</span>
        </label>
    </li>

    <!-- BAY -->
    <li class="item">
        <input id="internet_banking_bay" type="radio" name="offsite" value="internet_banking_bay" />
        <label for="internet_banking_bay">
            <div class="omise-logo-wrapper bay">
                <img class="bay" />
            </div>
            <span>Krungsri Bank</span>
        </label>
    </li>

    <!-- BBL -->
    <li class="item">
        <input id="internet_banking_bbl" type="radio" name="offsite" value="internet_banking_bbl" />
        <label for="internet_banking_bbl">
            <div class="omise-logo-wrapper bbl">
                <img class="bbl" />
            </div>
            <span>Bangkok Bank</span>
        </label>
    </li>
</ul>
