name: SonarCloud
on:
  workflow_run:
    workflows: [Code Coverage]
    branches: [master, feature/ENGA3-280-code-coverage]
    types: 
      - completed
      
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/download-artifact@master
      with:
        name: code-coverage
        path: reports
  
    - name: 'Unzip artifact'
      run: unzip code-coverage.zip 
        
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
